// Writes src/environments/environment.ts from NG_APP_BFF_BASE_URL (QP-ANGWEB-BFF-01).
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const TARGET = new URL('../src/environments/environment.ts', import.meta.url);

/** Returns the validated BFF base URL, or undefined to keep the committed default. */
export function resolveBffBaseUrl(env) {
  const raw = env.NG_APP_BFF_BASE_URL?.trim();
  if (!raw) {
    if (env.VERCEL) {
      throw new Error('NG_APP_BFF_BASE_URL is required on Vercel');
    }
    return undefined;
  }
  let url;
  try {
    url = new URL(raw);
  } catch {
    throw new Error(`NG_APP_BFF_BASE_URL is not an absolute URL: ${raw}`);
  }
  if (url.protocol !== 'https:') {
    throw new Error('NG_APP_BFF_BASE_URL must use https');
  }
  return raw.replace(/\/+$/, '');
}

export function renderEnvironment(bffBaseUrl) {
  return `// Generated by scripts/set-env.mjs. Do not edit.
export const environment = {
  bffBaseUrl: '${bffBaseUrl}',
};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const bffBaseUrl = resolveBffBaseUrl(process.env);
  if (bffBaseUrl) {
    writeFileSync(TARGET, renderEnvironment(bffBaseUrl));
  }
}
