// Writes src/environments/environment.ts from NG_APP_BFF_BASE_URL (QP-ANGWEB-BFF-01). With the
// variable unset it restores the local default, so a build against a remote BFF never leaks into
// the next local run. The generated file is committed with the default content; the test
// "the committed environment file is the generated local default" fails if anything else is
// committed by accident.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const DEFAULT_BFF_BASE_URL = 'http://localhost:8080';

const TARGET = new URL('../src/environments/environment.ts', import.meta.url);

/** Returns the validated BFF base URL (the local default when the variable is unset). */
export function resolveBffBaseUrl(env) {
  const raw = env.NG_APP_BFF_BASE_URL?.trim();
  if (!raw) {
    if (env.VERCEL) {
      throw new Error('NG_APP_BFF_BASE_URL is required on Vercel');
    }
    return DEFAULT_BFF_BASE_URL;
  }
  let url;
  try {
    url = new URL(raw);
  } catch {
    throw new Error(`NG_APP_BFF_BASE_URL is not an absolute URL: ${raw}`);
  }
  if (url.protocol !== 'https:') {
    throw new Error('NG_APP_BFF_BASE_URL must use https');
  }
  if (url.username || url.password || url.search || url.hash) {
    throw new Error(
      'NG_APP_BFF_BASE_URL must be a base URL without credentials, query or fragment',
    );
  }
  // href is the normalized form: the URL parser already drops tabs and newlines.
  return url.href.replace(/\/+$/, '');
}

export function renderEnvironment(bffBaseUrl) {
  // JSON.stringify yields a valid string literal for any value (quotes, newlines, backslashes).
  return `// Generated by scripts/set-env.mjs. Do not edit.
export const environment = {
  bffBaseUrl: ${JSON.stringify(bffBaseUrl)},
};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(TARGET, renderEnvironment(resolveBffBaseUrl(process.env)));
}
