// Writes src/environments/environment.ts from NG_APP_BFF_BASE_URL (QP-ANGWEB-BFF-01).
// Default: same-origin (empty base URL). The browser calls /bff/* on its own origin and the
// platform forwards it to the backend: Vercel via vercel.json rewrites, `ng serve` via
// proxy.conf.json. An absolute https URL is still accepted for a BFF on another origin.
// With the variable unset it restores the default, so a build against a remote BFF never leaks
// into the next local run. The generated file is committed with the default content; the test
// "the committed environment file is the generated same-origin default" fails if anything else
// is committed by accident.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

export const DEFAULT_BFF_BASE_URL = '';

const TARGET = new URL('../src/environments/environment.ts', import.meta.url);

/** Returns the validated BFF base URL ('' = same-origin when the variable is unset or '/'). */
export function resolveBffBaseUrl(env) {
  const raw = env.NG_APP_BFF_BASE_URL?.trim();
  if (!raw || raw === '/') {
    return DEFAULT_BFF_BASE_URL;
  }
  let url;
  try {
    url = new URL(raw);
  } catch {
    throw new Error(`NG_APP_BFF_BASE_URL is not an absolute URL: ${raw}`);
  }
  if (url.protocol !== 'https:') {
    throw new Error('NG_APP_BFF_BASE_URL must use https');
  }
  if (url.username || url.password) {
    throw new Error('NG_APP_BFF_BASE_URL must be a base URL without credentials');
  }
  // The parser reports an empty query or fragment ("/?", "/#") as empty strings: test the raw text.
  if (raw.includes('?')) {
    throw new Error('NG_APP_BFF_BASE_URL must be a base URL without a query string');
  }
  if (raw.includes('#')) {
    throw new Error('NG_APP_BFF_BASE_URL must be a base URL without a fragment');
  }
  // href is the normalized form: the URL parser already drops tabs and newlines.
  return url.href.replace(/\/+$/, '');
}

/**
 * One build-log line stating which mode the build uses, so a stale NG_APP_BFF_BASE_URL left in the
 * Vercel project (it would bypass the same-origin rewrite) is visible in the deployment log.
 */
export function describeBffMode(bffBaseUrl, env) {
  if (bffBaseUrl === '') {
    return 'set-env: BFF mode = same-origin (/bff/* is forwarded by the platform)';
  }
  const line = `set-env: BFF mode = absolute URL ${bffBaseUrl} (cross-origin)`;
  return env.VERCEL
    ? `${line}
set-env: WARNING NG_APP_BFF_BASE_URL is set on Vercel: remove it to use the same-origin rewrite from vercel.json`
    : line;
}

export function renderEnvironment(bffBaseUrl) {
  // JSON.stringify yields a valid string literal for any value (quotes, newlines, backslashes).
  return `// Generated by scripts/set-env.mjs. Do not edit.
export const environment = {
  bffBaseUrl: ${JSON.stringify(bffBaseUrl)},
};
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const bffBaseUrl = resolveBffBaseUrl(process.env);
  writeFileSync(TARGET, renderEnvironment(bffBaseUrl));
  process.stdout.write(`${describeBffMode(bffBaseUrl, process.env)}
`);
}
